planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

global_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 1.0
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
